### PR TITLE
Change: Remove SKU column from table of Transfer Hardware Card

### PR DESCRIPTION
**Pull request by baconYao**
As we discussed in Sprint, the SKU column is useless, therefore, remove it.

What I did in this commit is updating the template of table.

The following screenshot shows the final columns in table.

Screenshot from 2023-06-08 08-25-54

### CODE REVIEW

**Review by hanhsuan — APPROVED** [review]
LGTM

**Comment by scotthu27** [comment]
LGTM

**Review by scotthu27 — APPROVED** [review]
LGTM

**Comment by LiaoU3** [comment]
Are there gonna be so many commit after this PR?

**Review by seankingyang — COMMENTED** [review]
LGTM

**Review by seankingyang — APPROVED** [review]

**Review by clairlin53 — APPROVED** [review]
LGTM

**Comment by baconYao** [comment]
> Are there gonna be so many commit after this PR?

It's because the synchronization between my personal laptop, repo and  working laptop and generic oem-qa-tools repo

**Review by stanley31huang — APPROVED** [review]
LGTM

**Pull request merged**
