### PR TITLE
Update the style of HW transfer card

### PR DESCRIPTION
**Pull request by baconYao**
1. Update the style of Test Result field of HW transfer to cert lab card
2. Add back the missing comma

**No need to review the code under `templates` folder because it's the style I copied from Jira directly.**

The final style is like the picture.

style_of_test_result_field

### CODE REVIEW

**Review by weizhenwu — APPROVED** [review]
LGTM

**Review by seankingyang — APPROVED** [review]
LGTM ~~

**Comment by hanhsuan** [comment]
Using flake8 that what checkbox used to check the code, I got the following warning:
```shell
README.md:11:2: E999 SyntaxError: invalid character '├' (U+251C)
scenarios/pc/templates/transfer_hw_template.py:1:80: E501 line too long (85 > 79 characters)
tests/test_base_api.py:21:1: W293 blank line contains whitespace
tests/test_base_api.py:143:37: W291 trailing whitespace
tests/test_base_api.py:318:1: E305 expected 2 blank lines after class or function definition, found 1
tests/__init__.py:16:50: W291 trailing whitespace

```

**Comment by baconYao** [comment]
> Using flake8 that what checkbox used to check the code, I got the following warning:
> 
> ```shell
> README.md:11:2: E999 SyntaxError: invalid character '├' (U+251C)
> scenarios/pc/templates/transfer_hw_template.py:1:80: E501 line too long (85 > 79 characters)
> tests/test_base_api.py:21:1: W293 blank line contains whitespace
> tests/test_base_api.py:143:37: W291 trailing whitespace
> tests/test_base_api.py:318:1: E305 expected 2 blank lines after class or function definition, found 1
> tests/__init__.py:16:50: W291 trailing whitespace
> ```

Hi @hanhsuan,

I fixed most of flake8 errors except the E999, I will find a proper way to configure it in the future.
The interesting thing is Checkbox README also has this problem, but the structure is directly copied from `tree` command.

**Review by hanhsuan — APPROVED** [review]
LGTM

**Comment by scotthu27** [comment]
Can add one more Model name field for more detail?

CID | Model name | SKU Name | Location
-- | -- | -- | --
MandatoryExample: 202311-12345 | Example: Precision 5680 | OptionalExample: Canonical-Like-DVT2 | MandatoryExample: TEL-L3-F23-S5-P1
  |   |   |

**Pull request merged**
