### PR TITLE
Add checking net MAC after installing checkbox-ng

### PR DESCRIPTION
**Pull request by hanhsuan**
This feature is for checking MAC of net devices are in black list or not. It won't stop installing process, but notice user to check only.

### CODE REVIEW

**Comment by baconYao** [comment]
It's a good feature. But, may I know what's the purpose of this checking while installing oem-checkbox provider?

**Comment by hanhsuan** [comment]
Normally, the MAC will be changed while updating BIOS only, then we will reinstall OS and checkbox for further testing. Therefore, I thought we could check MAC at this step.

**Comment by hanhsuan** [comment]
Yes, it is for installing OS via USB key.

**Comment by baconYao** [comment]
Got it.

However, in my opinion, this script is not suitable here, the aim of **oem-qa-checkbox-installer** should stick on the **provider installation**.  Do you think is it possible that this feature to be a standalone script instead of a part of oem-qa-checkbox-installer?

> What will happen while only one MAC is wrong in multiple Ethernet port then deploy OS via Jenkins?

I have no idea actually. We should check with SWE to know what will happen.

**Comment by hanhsuan** [comment]
Sure. This script is standalone at first. Do you have any suggestion place to put this script and config file?

**Comment by baconYao** [comment]
I suggest you can create a folder under `Tools/PC/` and put your scripts there.

**Comment by weizhenwu** [comment]
In my opinion, checking MAC address should be done right after updating the BIOS.
so no matter if you install OS via Jenkins or USB key, they should be online on HIC before that.

**Comment by stanley31huang** [comment]
Agreed with Weizhen, we should have a EFI shell script to save MAC and update the original MAC back after updating the BIOS.
So we could make sure the system has the same MAC addresses, and the HIC could recognized it without any issue.

**Comment by hanhsuan** [comment]
I find [EFI command list](https://docstore.mik.ua/manuals/hp-ux/en/5991-1247B/ch04s13.html), and We could use `lanaddress` command to get all MAC. So, the next step is changing this script to a standalone EFI script right ?

**Comment by weizhenwu** [comment]
generally, **somerville** will provide MAC address restore script along with BIOS update file.
**stella** uses .cab in most of the cases instead of EFI update.
but I'm not sure about sutton, @stanley31huang @baconYao could you help to confirm?

anyway, I think developing an EFI script could be helpful but not a priority. also, it will be another topic so I suggest we close this PR without merging for now.

**Pull request closed without merging**
